language: crystal
services:
  - redis-server
addons:
  apt:
    packages:
      - redis-server
before_install:
  - sudo sed -e 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf > redis.conf
  - sudo mv redis.conf /etc/redis
  - sudo service redis-server start
  - echo PING | nc localhost 6379
script:
  - make test
